### ISSUE TITLE
cargo-sphinx fails on projects without Cargo.toml configuration set.

### ISSUE THREAD

**Issue by daithiocrualaoich** [woofwoofinc/cargo-sphinx#26]
```
$ cargo new fatal
$ cd fatal
$ cargo sphinx
error: Fatal: Invalid cargo file format.
```

**Comment by passy** [comment]
What should happen here? More informative error message or more?

**Comment by daithiocrualaoich** [comment]
It worked when "[package.metadata.sphinx]" is added to Cargo.toml. Tool should not fail if this is not present in Cargo.toml.

**Comment by daithiocrualaoich** [comment]
https://github.com/woofwoofinc/cargo-sphinx/blob/master/src/config.rs#L78 shouldn't be assuming a parse error if the option is not an Ok.

**Comment by passy** [comment]
Is the return type of `from` insufficient, perhaps? Would having it as `Option<Result<_, _>>` help?

**Comment by daithiocrualaoich** [comment]
That should be fine. Currently battling with the borrowchecker but want an option in the struct instead, I think:

```
pub struct Config {
    toml: Option<Table>,
}
```

**Comment by passy** [comment]
Good luck!

**Comment by daithiocrualaoich** [comment]
OMG... I've cheated this like a master villain! :)
