### ISSUE TITLE
Cargo sphinx fails without explanation

### ISSUE THREAD

**Issue by plauche** [woofwoofinc/cargo-sphinx#83]
Hey,

I was following the [tutorial](https://woofwoofinc.github.io/cargo-sphinx/tutorial.html) and found that `cargo sphinx` failed pretty immediately without any helpful messages.

    $ cargo new project
    $ cd project
    $ sphinx-quickstart
    $ cargo sphinx
    error: Fatal: No such file or directory (os error 2)

I encountered this error when installing using `cargo install cargo-sphinx` and when building+installing from the latest source.

**Comment by passy** [comment]
Sorry for the delay, @plauche. I've only just noticed the issue here.

Could you let me know what operating system you're on and your version of Rust/Cargo. I'm not quite sure what's going on there, but would like to try and reproduce this.

**Comment by daithiocrualaoich** [comment]
Thanks. The Sphinx Quickstart tool used to configure the docs directory path interactively but in more recent versions it has to be provided as a command line argument.

I've updated the documentation in #124. Will leave this issue here until we add some better error messaging.

Thanks.

**Comment by daithiocrualaoich** [comment]
I'll put out a 1.3.1 later today or tomorrow with this change.
